version: "3.9"
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: container_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./models
        target: /app/models
    env_file: 
      - .env

  airflow-webserver:
    image: apache/airflow:2.1.1
    container_name: airflow_webserver
    command: webserver
    env_file: 
      - .env
    volumes:
      - ./flow/dags:/opt/airflow/dags
      - ./flow/logs:/opt/airflow/logs
      - ./flow/plugins:/opt/airflow/plugins
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./models
        target: /app/models
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.1.1
    container_name: airflow_scheduler
    command: scheduler
    env_file: 
      - .env
    volumes:
      - ./flow/dags:/opt/airflow/dags
      - ./flow/logs:/opt/airflow/logs
      - ./flow/plugins:/opt/airflow/plugins
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./models
        target: /app/models
    depends_on:
      - airflow-init
      - postgres

  airflow-init:
    image: apache/airflow:2.1.1
    container_name: airflow_init
    env_file: 
      - .env
    volumes:
      - ./flow/dags:/opt/airflow/dags
      - ./flow/logs:/opt/airflow/logs
      - ./flow/plugins:/opt/airflow/plugins
      - ./flow/airflow_variables.json:/opt/airflow/airflow_variables.json
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --role Admin --username admin --email admin@example.com --firstname admin --lastname admin --password admin &&
               airflow variables import /opt/airflow/airflow_variables.json"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_airflow
    env_file: 
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
